### ISSUE TITLE
ex/board/nowのResponseフォーマットについて

### ISSUE THREAD

**Issue by nyatla** [namuyan/nem-tip-bot-console#1]
板情報について、typeで種別を判定するよりも、種別ごとに分けて配列を作ったほうがいいと思います。
data:[
 {type=sell...}
 {type=sell...}
 {type=buy...}
：
]
↓
data:[
sell: [
  item,item,...
]
buy:[
  item,item,...
]
sellとbuyの要素は、それぞれ価格で昇順、降順になってると良いです。(0で末端価格を取得できるので)
板が存在しなければ空の配列を返してください。

理由は取引所のAPIの戻り値が大体この形式であるからです。

**Comment by namuyan** [comment]
有難うございます！
早速コードを修正し反映させました。
